### ISSUE TITLE
Presentation is not public

### ISSUE THREAD

**Issue by BukT0p** [dmytrodanylyk/template#2]
The presentation is not public, please share [img](https://www.dropbox.com/s/vr0xf5veab6y32p/Screenshot%202017-02-20%2013.30.31.png)

**Comment by dmytrodanylyk** [comment]
Hi, presentation will be available on Feb 23.

**Comment by dmytrodanylyk** [comment]
Uploaded: https://speakerdeck.com/dmytrodanylyk/configuring-android-project
